spring.application.name=BMS


spring.datasource.url=jdbc:mysql://localhost:3306/BMS?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080



---------------------------------
core java:

multithreading
collections
oops
exception

advance java:
jdbc
servlet

spring core
spring boot
jpa
REST


























